### ISSUE TITLE
Solution is discoverable in a hacky way

### ISSUE THREAD

**Issue by Khelavaster** [NUKnightLab/sql-mysteries#15] opened 2019-12-16 23:23 UTC
In the second query example that is meant to discover the database structure, you can delete the WHERE clause, which prints the trigger text containing the solution values and methods of obtaining them. From there you can just execute SELECT * FROM person WHERE hex(name) = '4D6972...' to get the solution.

Perhaps it could be hidden somewhere outside the database.

**Comment by JoeGermuska** [comment] 2019-12-17 16:39
Duplicate of #13  / in short, this is more of a feature than a bug, and definitely something where we don't see the value of investing energy.

**Closed by JoeGermuska** 2019-12-17 16:39 UTC
Labels: wontfix

**Comment by Med-Yassine-B** [comment] 2026-09-04 20:33
@JoeGermuska 
i suggest hashing the solution instead of using a hex encoding
```sql
WHEN hex(sha256(lower(trim(new.value)))) == 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
```
something like this will make it harder for player to hack so they dont just plug the value into a hex decodes
after all i like yout work 🙌
